### ISSUE TITLE
Launching The ModPack

### ISSUE THREAD

**Issue by Gemlover2014** [ProjectSynchro/WalrusRPG#2]
When I try to launch the mod pack all it does is open the mojang screen it stays there for a few seconds and then it closes and goes back to the technic launcher

**To Reproduce**
1. Go to Mod Packs
2. Click on Play
3. Mojang screen opens
4. And then it closes

I thought it was going to open

 - Windows 10
 - Modpack Version 3.2.2

**Comment by ProjectSynchro** [comment]
Would you be able to attach the crash log? (that would be in the crash-reports folder in your modpack folder)

**Comment by Gemlover2014** [comment]
[crash-2020-11-10_09.39.42-client.txt](https://github.com/ProjectSynchro/WalrusRPG/files/5532567/crash-2020-11-10_09.39.42-client.txt)

**Comment by ProjectSynchro** [comment]
@Gemlover2014 I see the issue now, it seems that bspkrscore is checking for a version file.. and since the version is too old and said file doesn't exist on the internet.. the mod developer makes the mod crash the game..
This should be fixed with commit https://github.com/ProjectSynchro/WalrusRPG/commit/79c24a0b73730bc24384cdf4355164cd4beee22e
But I'll do some additional testing to see if it's something else.

**Comment by ProjectSynchro** [comment]
I have pushed an update to Technic and I have release an updated MultiMC release here:
https://github.com/ProjectSynchro/WalrusRPG/releases/tag/v3.2.3
Try updating the pack and let me know if your issue is fixed, closing this for now
